# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CCU/DigitalSys/DDlab12/Lab12DemoV1.0_3/Lab12Demo.srcs/sources_1/ip/clkwiz0/clkwiz0.xci
# IP: The module: 'clkwiz0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CCU/DigitalSys/DDlab12/Lab12DemoV1.0_3/Lab12Demo.srcs/sources_1/ip/clkwiz0/clkwiz0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkwiz0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/CCU/DigitalSys/DDlab12/Lab12DemoV1.0_3/Lab12Demo.srcs/sources_1/ip/clkwiz0/clkwiz0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkwiz0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/CCU/DigitalSys/DDlab12/Lab12DemoV1.0_3/Lab12Demo.srcs/sources_1/ip/clkwiz0/clkwiz0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkwiz0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/CCU/DigitalSys/DDlab12/Lab12DemoV1.0_3/Lab12Demo.srcs/sources_1/ip/clkwiz0/clkwiz0.xci
# IP: The module: 'clkwiz0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CCU/DigitalSys/DDlab12/Lab12DemoV1.0_3/Lab12Demo.srcs/sources_1/ip/clkwiz0/clkwiz0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkwiz0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/CCU/DigitalSys/DDlab12/Lab12DemoV1.0_3/Lab12Demo.srcs/sources_1/ip/clkwiz0/clkwiz0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkwiz0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/CCU/DigitalSys/DDlab12/Lab12DemoV1.0_3/Lab12Demo.srcs/sources_1/ip/clkwiz0/clkwiz0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkwiz0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
