######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 18 13:12:03 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp
